### ISSUE TITLE
Question regarding n_batches

### ISSUE THREAD

**Issue by yuvalH9** [khornlund/pytorch-balanced-sampler#1]
Hi @khornlund ,

First of all I must say that this is a very usefull tool, thanks for that!

I wanted to ask how to deal with the case of `dataSet.__len__() / n_batch_size` is not an integer?
We just give up on last batch or we can do something else? 

thanks,
Yuval

**Comment by khornlund** [comment]
I don't think you need to worry about this, because we are sampling with replacement anyway.

When you sample with replacement it isn't obvious how long an epoch should be. Instead, the length of an epoch is set using the batch size and the number of batches.
