### ISSUE TITLE
not working on 2 classes

### ISSUE THREAD

**Issue by vangorade** [khornlund/pytorch-balanced-sampler#2]
-----------dataloader setting--------------------
batch_size: 5
epoch_size: 10
data_dir: data
num_workers: 2
validation_split: 0.10
img_size: 256
alpha: 1
kind: "fixed"

dataset shape -> (x, meta), y
----------------printed shape-----------------------
x = torch.Size([5, 3, 256, 256])  meta = torch.Size([5, 9])
torch.Size([5, 3, 256, 256]) torch.Size([5, 9])
torch.Size([5, 3, 256, 256]) torch.Size([5, 9])
torch.Size([5, 3, 256, 256]) torch.Size([5, 9])
torch.Size([5, 3, 256, 256]) torch.Size([5, 9])
torch.Size([5, 3, 256, 256]) torch.Size([5, 9])
torch.Size([5, 3, 256, 256]) torch.Size([5, 9])
torch.Size([5, 3, 256, 256]) torch.Size([5, 9])
torch.Size([5, 3, 256, 256]) torch.Size([5, 9])
torch.Size([3, 256, 256]) torch.Size([3, 256, 256])
------------------------------------------------------------------
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [32, 3, 3, 3], but got 3-dimensional input of size [3, 257, 257] instead

how can i remove epoch_size from data loader ? when i remove it or set it None it throws error at
oversample_rates = proportions_of_samples_per_batch * n_batches  this line

**Comment by khornlund** [comment]
You can't. Since we are over/under sampling, the size of an epoch is not necessarily the same as the number of samples you have, so you need to specify it.
